spring.application.name=client

spring.cloud.aws.dynamodb.endpoint=http://localhost:8000
spring.cloud.aws.region.static=eu-west-1
spring.cloud.aws.credentials.access-key=local
spring.cloud.aws.credentials.secret-key=local
