spring.application.name=client

#El endpoint de nuestra base de datos, que la tenemos desplegada en Docker
spring.cloud.aws.dynamodb.endpoint=http://localhost:8000

#La región recomendada es Irlanda
spring.cloud.aws.region.static=eu-west-1

#Tenemos la base de datos desplegada en local, estos son los credenciales
spring.cloud.aws.credentials.access-key=local
spring.cloud.aws.credentials.secret-key=local